default_stages: [ pre-commit, manual ]

repos:
  - repo: https://github.com/ambv/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args:
          - --config=.code_quality/.flake8

  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.10' # Update me!
    hooks:
      - id: bandit
        args:
          - "--skip"
          - "B311"
          - "-x"
          - "test/**"
          - "--skip"
          - "B104"
          - "--skip"
          - "B311"
          - "--skip"
          - "B101"


#residente del mal 8 pueblo
#r
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args:
          - --config-file=.code_quality/mypy.ini
        additional_dependencies:
          - types-PyMySQL
          - types-requests
          - types-cachetools
          - types-pyyaml